### ISSUE TITLE
DELETE request does not delete minimal server tasks

### ISSUE THREAD

**Issue by youph** [data61/stellar-evaluation-plugins#15]
In celery server case, DELETE request sent to, e.g., representation_learning task, deletes the task.
In minimal server case, it does not!
After the DELETE request is sent to the minimal server task, the task state changes to "STOPPING", but the task continues to run, until completion, upon which the task state is updated to "SUCCESS".

In celery server case, after the DELETE request is sent to the task, its state immediately changes to "REVOKED", and the task is stopped.

**Comment by adocherty** [comment]
The minimal server doesn't proactively kill workers, it only stops them when control is returned to the handler during a `worker.update_state` call.  This is not ideal, but I haven't figured out how to kill a multiprocessing worker and restart another yet.

To fix this will be tricky, and we may have to investigate other multiprocessing models.  A stop-gap solution is to ensure the task calls `worker.update_state` frequently.

**Comment by youph** [comment]
Ok, I see; yet the final state of the task that has been stopped should not be "SUCCESS", still. If it was "STOPPING" in the interim, it should become something like "REVOKED" or "CANCELED", right?
Compare with the same process of deleting a task in celery server case.

**Comment by adocherty** [comment]
Yes, good point. It will be REVOKED if there is a call to update_state. However, there is a bug that if there are no calls to update_state it never gets to the cancellation logic.

That can be fixed - we can check if the task returns normally but there is a delete request, we can throw away the results and make the task as REVOKED?

**Comment by youph** [comment]
Yes, this would work I guess.

**Comment by adocherty** [comment]
I've changed the way minimal_server does task deletion to fix this bug in commit 7a0c258454a38d13d1d5635a69cf68aa5b8968a9

The minimal_server now deletes the worker processing a task and then respawns a new worker. This sends a SIGTERM to the process so can leave any files the worker is using in an unknown state.

Additionally, there is some chance that the queues used to communicate between processes can be corrupted (see [docs](https://docs.python.org/3.6/library/multiprocessing.html#multiprocessing.Process.terminate)). However, I use locks when the workers access these queues to prevent this. It hasn't been extensively tested, however.
