### ISSUE TITLE
Plugins to return POST call args in addition to task results

### ISSUE THREAD

**Issue by youph** [data61/stellar-evaluation-plugins#5]
I think it would be useful for all plugins (starting from dummy plugin) to return not just the task results, but also the arguments it was passed in the POST call, in line with the plugins in serene-fugu-server repo.

**Comment by adocherty** [comment]
This is now implemented for Celery server. It now returns 'args' as well as 'results' in the JSON data after the task has finished. the args contains the raw arguments that were sent to the task: including "inputs", "output", and "parameters".

This was a bug as the minimal server correctly implemented this function.
